/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

"use client";

import React, { useState } from "react";
import Link from 'next/link';
import { motion, AnimatePresence } from "motion/react";
import { 
  ChevronDown, 
  ArrowRight, 
  ShieldCheck, 
  Clock, 
  HelpCircle, 
  Lock, 
  Eye, 
  Database,
  CheckCircle2
} from "lucide-react";

interface PolicySection {
  id: string;
  title: string;
  content: string;
}

export function PrivacyPolicy() {
  const [openSection, setOpenSection] = useState<string | null>("info-collect");

  const policySections: PolicySection[] = [
  {
    id: "definitions",
    title: "1. Definitions and Key Terms",
    content: `To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:

• Cookie: Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
• Company: When this policy mentions “Company,” “we,” “us,” or “our,” it refers to Analytics Clouds, 917, C/o PREM SHANKAR, IDGAH ROAD, GANDHI NAGAR, Unnao, Unnao, Uttar Pradesh, 209801 that is responsible for your information under this Privacy Policy.
• Country: Where Analytics Clouds or the owners/founders of Analytics Clouds are based, in this case is India.
• Customer: Refers to the company, organization or person that signs up to use the Analytics Clouds Service to manage the relationships with your consumers or service users.
• Device: Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Analytics Clouds and use the services.
• IP Address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
• Personnel: Refers to those individuals who are employed by Analytics Clouds or are under contract to perform a service on behalf of one of the parties.
• Personal Data: Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
• Service: Refers to the service provided by Analytics Clouds as described in the relative terms (if available) and on this platform.
• Third-party Service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
• Website: Analytics Clouds’s site, which can be accessed via this URL: https://www.analyticsclouds.com/.
• You: A person or entity that is registered with Analytics Clouds to use the Services.`
  },
  {
    id: "info-collect",
    title: "2. What Information Do We Collect?",
    content: `We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form:

• Name / Username
• Phone Numbers
• Email Addresses`
  },
  {
    id: "how-use",
    title: "3. How Do We Use The Information We Collect?",
    content: `Any of the information we collect from you may be used in one of the following ways:

• To personalize your experience (your information helps us to better respond to your individual needs)
• To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)
• To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)
• To process transactions
• To administer a contest, promotion, survey or other site feature
• To send periodic emails`
  },
  {
    id: "third-party-info",
    title: "4. When do we use customer information from third parties?",
    content: `We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming our customer, we receive information from a third party that provides automated fraud detection services to us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.`
  },
  {
    id: "data-sharing",
    title: "5. Do we share the information we collect with third parties?",
    content: `We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.

We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our service. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.

We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the service in a shared location, and type of device used to visit the service. They may aggregate information about our advertising and what you see on the service and then provide auditing, research and reporting for us and our advertisers.

We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.`
  },
  {
    id: "where-when-collected",
    title: "6. Where and when is information collected from customers and end users?",
    content: `We will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.`
  },
  {
    id: "email-usage",
    title: "7. How Do We Use Your Email Address?",
    content: `By submitting your email address on our service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do.

By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us.

Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy.

Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.`
  },
  {
    id: "international-transfer",
    title: "8. Could my information be transferred to other countries?",
    content: `We are incorporated in India. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.`
  },
  {
    id: "data-security",
    title: "9. Is the information collected through our service secure?",
    content: `We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.`
  },
  {
    id: "updating-information",
    title: "10. Can I update or correct my information?",
    content: `The rights you have to request updates or corrections to the information we collect depend on your relationship with us. Personnel may update or correct their information as detailed in our internal company employment policies.

Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.

To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.

If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.`
  },
  {
    id: "personnel",
    title: "11. Personnel",
    content: `If you are one of our workers or applicants, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants. You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.`
  },
  {
    id: "sale-of-business",
    title: "12. Sale of Business",
    content: `We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.`
  },
  {
    id: "affiliates",
    title: "13. Affiliates",
    content: `We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, “Corporate Affiliate” means any person or entity which directly or indirectly controls, is controlled by or is under common control with us, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.`
  },
  {
    id: "data-retention",
    title: "14. How Long Do We Keep Your Information?",
    content: `We keep your information only so long as we need it to provide service to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can’t identify you.`
  },
  {
    id: "protect-information",
    title: "15. How Do We Protect Your Information?",
    content: `We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file.

We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.`
  },
  {
    id: "governing-law",
    title: "16. Governing Law",
    content: `The laws of India, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.`
  },
  {
    id: "your-consent",
    title: "17. Your Consent",
    content: `By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.`
  },
  {
    id: "links-other-websites",
    title: "18. Links to Other Websites",
    content: `This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by us. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.`
  },
  {
    id: "cookies",
    title: "19. Cookies",
    content: `We use “Cookies” to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.`
  },
  {
    id: "remarketing",
    title: "20. Remarketing Services",
    content: `We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they’re “following” people around the internet by serving ads on the websites and platforms they use most.`
  },
  {
    id: "kids-privacy",
    title: "21. Kids' Privacy",
    content: `We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from our servers.`
  },
  {
    id: "policy-changes",
    title: "22. Changes To Our Privacy Policy",
    content: `If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.`
  },
  {
    id: "third-party-services",
    title: "23. Third-Party Services",
    content: `We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (“Third-Party Services”).

You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.

Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties’ terms and conditions.`
  },
  {
    id: "facebook-pixel",
    title: "24. Facebook Pixel",
    content: `Facebook pixel is an analytics tool that allows you to measure the effectiveness of your advertising by understanding the actions people take on your website. You can use the pixel to: Make sure your ads are shown to the right people. Facebook pixel may collect information from your device when you use the service. Facebook pixel collects information that is held in accordance with its Privacy Policy.`
  },
  {
    id: "contact-us",
    title: "25. Contact Us",
    content: `Don’t hesitate to contact us if you have any questions.

• Via Email: sales@analyticsclouds.com`
  }
];

  const toggleSection = (id: string) => {
    setOpenSection(openSection === id ? null : id);
  };

  return (
    <div id="privacy-policy-page-container" className="bg-white text-[#333333] selection:bg-[#FE7146] selection:text-white">

      {/* 1. Hero Section (dark navy band, extends behind the fixed navbar — no white gap) */}
      <section id="privacy-hero-section" className="bg-[#303360] text-white pt-28 pb-16 sm:pt-32 sm:pb-20 relative overflow-hidden">
        
        {/* Subtle background decoration (low opacity orange gradient and dots) */}
        <div className="absolute inset-0 z-0 opacity-15 pointer-events-none">
          <div className="absolute top-1/2 right-10 -translate-y-1/2 w-96 h-96 bg-[#FE7146] rounded-full filter blur-3xl" />
          <div className="absolute inset-0 bg-[radial-gradient(#ffffff_1px,transparent_1px)] [background-size:24px_24px] opacity-10" />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center space-y-6">
          
          {/* Small pill badge */}
          <div className="inline-block bg-white text-[#303360] text-[10px] sm:text-xs font-black tracking-widest uppercase px-4 py-1.5 rounded-full shadow-md">
            Your Privacy Matters to Us
          </div>

          {/* Headline */}
          <h1 className="font-display font-extrabold text-4xl sm:text-5xl lg:text-6xl text-white tracking-tight leading-tight">
            Privacy Policy
          </h1>

          {/* Subcopy */}
          <p className="text-gray-300 text-sm sm:text-base font-normal max-w-2xl mx-auto leading-relaxed">
            Learn how Analytics Clouds handles, secures, and respects your business metrics, personal identifiers, and user preferences on our platform.
          </p>

        </div>
      </section>

      {/* 2. Breadcrumb bar */}
      <section id="privacy-breadcrumb-bar" className="bg-[#F5F5FA] border-b border-gray-100 py-3 text-left">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-xs font-semibold text-gray-500 flex items-center gap-2">
          <Link href="/" className="text-[#303360] hover:text-[#FE7146] transition-colors">
            Home
          </Link>
          <span className="text-gray-400 font-normal">&gt;</span>
          <span className="text-[#FE7146] font-bold">Privacy Policy</span>
        </div>
      </section>

   

      {/* 4. Privacy Accordion (Main Content) */}
      <section id="privacy-content-section" className="py-16 sm:py-20 bg-white relative">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          
          {/* Header metadata row */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-100 pb-6 mb-10">
            <div className="flex items-center gap-2 text-slate-500 font-semibold text-xs">
              <Clock size={14} className="text-[#FE7146]" />
              <span>Last Updated: July 2026</span>
            </div>
           
          </div>

          {/* Accordion List */}
          <div className="space-y-4">
            {policySections.map((sec) => {
              const isOpen = openSection === sec.id;
              
              return (
                <div
                  key={sec.id}
                  id={`accordion-item-${sec.id}`}
                  className={`border rounded-2xl transition-all duration-300 overflow-hidden bg-white ${
                    isOpen
                      ? "border-[#FE7146] shadow-md shadow-[#FE7146]/5"
                      : "border-gray-200 hover:border-gray-300 hover:bg-slate-50/50"
                  }`}
                >
                  
                  {/* Clickable Header Row */}
                  <button
                    onClick={() => toggleSection(sec.id)}
                    className="w-full px-6 py-4.5 sm:py-5 flex items-center justify-between gap-4 text-left cursor-pointer focus:outline-none min-h-[52px]"
                    aria-expanded={isOpen}
                  >
                    <span className={`font-display font-black text-sm sm:text-base transition-colors ${
                      isOpen ? "text-[#303360]" : "text-[#303360]/85"
                    }`}>
                      {sec.title}
                    </span>

                    {/* Rotating chevron indicator */}
                    <div className={`shrink-0 w-7 h-7 rounded-full border flex items-center justify-center transition-all duration-300 ${
                      isOpen 
                        ? "border-[#FE7146]/20 bg-[#FFF1EC] text-[#FE7146]" 
                        : "border-gray-200 bg-slate-50 text-slate-400"
                    }`}>
                      <ChevronDown
                        size={15}
                        className={`transition-transform duration-300 ${isOpen ? "rotate-180" : ""}`}
                      />
                    </div>
                  </button>

                  {/* Expandable Body Panel with height-animation */}
                  <AnimatePresence initial={false}>
                    {isOpen && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden border-t border-gray-100 bg-slate-50/20"
                      >
                        <div className="px-6 py-5 sm:py-6 text-gray-600 text-xs sm:text-sm font-normal leading-relaxed text-left whitespace-pre-wrap">
                          {sec.content}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>

                </div>
              );
            })}
          </div>

        </div>
      </section>

      {/* 5. "Still Have Questions?" Closing Strip */}
      <section id="privacy-questions-strip" className="py-12 bg-[#F5F5FA] border-t border-b border-gray-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-6">
          
          <div className="flex items-center gap-4 text-left">
            <div className="w-10 h-10 rounded-full bg-[#FFF1EC] text-[#FE7146] flex items-center justify-center shrink-0 shadow-sm">
              <HelpCircle size={20} />
            </div>
            <div>
              <h3 className="font-display font-black text-sm sm:text-base text-[#303360] leading-snug">
                Have questions about your data or privacy?
              </h3>
              <p className="text-gray-500 text-xs mt-0.5 font-medium">
                Our administration and compliance team is ready to answer any questions.
              </p>
            </div>
          </div>

          <Link href="/contact"
            className="w-full sm:w-auto bg-[#FE7146] hover:bg-[#e0562b] text-white font-extrabold text-xs px-6 py-3.5 rounded-xl shadow-md hover:shadow-lg hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center justify-center gap-1.5"
          >
            <span>Contact Our Team</span>
            <ArrowRight size={14} />
          </Link>

        </div>
      </section>

    </div>
  );
}
