/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

"use client";

import React, { useState } from "react";
import Link from 'next/link';
import { motion, AnimatePresence } from "motion/react";
import { ChevronDown, ArrowRight, ShieldCheck, Clock, FileText, HelpCircle } from "lucide-react";

interface TermsSection {
  id: string;
  title: string;
  content: string;
}

export function TermsOfService() {
  const [openSection, setOpenSection] = useState<string | null>("acceptance");

  const termsSections: TermsSection[] = [
  {
    id: "general-terms",
    title: "1. General Terms",
    content: `By accessing and placing an order with Analytics Clouds, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Analytics Clouds.

Under no circumstances shall Analytics Clouds team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Analytics Clouds team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.

Analytics Clouds will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.`
  },
  {
    id: "license",
    title: "2. License",
    content: `Analytics Clouds grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement. 

These Terms & Conditions are a contract between you and Analytics Clouds (“we,” “our,” or “us”) granting you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.`
  },
  {
    id: "definitions",
    title: "3. Definitions and Key Terms",
    content: `For this Terms & Conditions:

• Cookie: Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
• Company: When this policy mentions “Company,” “we,” “us,” or “our,” it refers to Analytics Clouds that is responsible for your information under this Privacy Policy.
• Country: Where Analytics Clouds or the owners/founders of Analytics Clouds are based, in this case is India.
• Customer: Refers to the company, organization or person that signs up to use the Analytics Clouds Service to manage the relationships with your consumers or service users.
• Device: Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Analytics Clouds and use the services.
• IP Address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
• Personnel: Refers to those individuals who are employed by Analytics Clouds or are under contract to perform a service on behalf of one of the parties.
• Personal Data: Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
• Service: Refers to the service provided by Analytics Clouds as described in the relative terms (if available) and on this platform.
• Third-Party Service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
• Website: Analytics Clouds’s site, which can be accessed via this URL: https://www.analyticsclouds.com/.
• You: A person or entity that is registered with Analytics Clouds to use the Services.`
  },
  {
    id: "restrictions",
    title: "4. Restrictions",
    content: `You agree not to, and you will not permit others to:

• License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the service or make the platform available to any third party.
• Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the service.
• Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Analytics Clouds or its affiliates, partners, suppliers or the licensors of the service.`
  },
  {
    id: "refund-policy",
    title: "5. Return and Refund Policy",
    content: `Thanks for shopping with us. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.

As with any shopping experience, there are terms and conditions that apply to transactions at our company. The main thing to remember is that by placing an order or making a purchase from us, you agree to the terms along with our Privacy Policy.

If, for any reason, You are not completely satisfied with any good or service that we provide, don’t hesitate to contact us and we will discuss any of the issues you are going through with our product.`
  },
  {
    id: "suggestions",
    title: "6. Your Suggestions",
    content: `Any feedback, comments, ideas, improvements or suggestions (collectively, “Suggestions”) provided by you to us with respect to the service shall remain the sole and exclusive property of Analytics Clouds. We shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.`
  },
  {
    id: "consent",
    title: "7. Your Consent",
    content: `We’ve updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it’s being used. By using our service, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.`
  },
  {
    id: "third-party-links",
    title: "8. Links to Other Websites",
    content: `Our service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Terms & Conditions of every site You visit. We have no control over and assume no responsibility for the content, Terms & Conditions or practices of any third party sites or services.`
  },
  {
    id: "cookies",
    title: "9. Cookies",
    content: `We use “Cookies” to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our platform as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.`
  },
  {
    id: "changes-to-terms",
    title: "10. Changes To Our Terms & Conditions",
    content: `You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service. 

You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date.`
  },
  {
    id: "service-modifications",
    title: "11. Modifications and Updates to Our Service",
    content: `We reserve the right to modify, suspend or discontinue, temporarily or permanently, the service or any service to which it connects, with or without notice and without liability to you.

We may from time to time provide enhancements or improvements to the features/functionality of the service, which may include patches, bug fixes, updates, upgrades and other modifications (“Updates”). Updates may modify or delete certain features and/or functionalities of the service. You agree that we have no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the service to you. You further agree that all Updates will be (i) deemed to constitute an integral part of the service, and (ii) subject to the terms and conditions of this Agreement.`
  },
  {
    id: "third-party-services",
    title: "12. Third-Party Services",
    content: `We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (“Third-Party Services”). You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.`
  },
  {
    id: "term-and-termination",
    title: "13. Term and Termination",
    content: `This Agreement shall remain in effect until terminated by you or us. We may, in our sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice. This Agreement will terminate immediately, without prior notice from us, in the event that you fail to comply with any provision of this Agreement. 

You may also terminate this Agreement by deleting the service and all copies thereof from your computer. Upon termination of this Agreement, you shall cease all use of the service and delete all copies of the service from your computer.`
  },
  {
    id: "copyright-infringement",
    title: "14. Copyright Infringement Notice",
    content: `If you are a copyright owner or such owner’s agent and believe any material from us constitutes an infringement on your copyright, please contact us setting forth the following information: 

• (a) A physical or electronic signature of the copyright owner or a person authorized to act on his behalf; 
• (b) Identification of the material that is claimed to be infringing; 
• (c) Your contact information, including your address, telephone number, and an email; 
• (d) A statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and 
• (e) A statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.`
  },
  {
    id: "indemnification",
    title: "15. Indemnification",
    content: `You agree to indemnify and hold us and our parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys’ fees, due to or arising out of your: (a) use of the service; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.`
  },
  {
    id: "no-warranties",
    title: "16. No Warranties",
    content: `The service is provided to you “AS IS” and “AS AVAILABLE” and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, we, on our own behalf and on behalf of our affiliates and our respective licensors and service providers, expressly disclaim all warranties, whether express, implied, statutory or otherwise, with respect to the service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement.

Without limiting the foregoing, neither us nor any provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the service; (ii) that the service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided; or (iv) that the service, its servers, or emails sent from or on behalf of us are free of viruses or other harmful components.`
  },
  {
    id: "limitation-of-liability",
    title: "17. Limitation of Liability",
    content: `Notwithstanding any damages that you might incur, the entire liability of us and any of our suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the service. 

To the maximum extent permitted by applicable law, in no event shall we or our suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including damages for loss of profits, loss of data or other information, for business interruption, or personal injury) arising out of or in any way related to the use of or inability to use the service.`
  },
  {
    id: "severability-and-waiver",
    title: "18. Severability & Waiver",
    content: `If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.

Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not affect a party’s ability to exercise such right at any time thereafter nor shall the waiver of a breach constitute waiver of any subsequent breach. YOU AND US AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.`
  },
  {
    id: "intellectual-property",
    title: "19. Intellectual Property",
    content: `Our platform and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by us, its licensors or other providers of such material and are protected by India and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. Any unauthorized use of the material is prohibited.`
  },
  {
    id: "dispute-resolution",
    title: "20. Dispute Resolution & Arbitration",
    content: `This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING INTELLECTUAL PROPERTY RIGHTS. 

• Notice of Dispute: In the event of a dispute, you or us must give the other a Notice of Dispute (a written statement with name, address, contact info, facts, and relief requested) via email to: [sales@analyticsclouds.com](mailto:sales@analyticsclouds.com). Both parties will attempt informal negotiation within sixty (60) days before commencing arbitration.
• Binding Arbitration: If not resolved by informal negotiation, any dispute will be conducted exclusively by binding arbitration in accordance with commercial arbitration rules. You are giving up the right to litigate disputes in court before a judge or jury.`
  },
  {
    id: "submissions-and-promotions",
    title: "21. Submissions & Promotions",
    content: `• Submissions: Any ideas, creative suggestions, designs, or proposals posted or submitted by you shall automatically become our sole property without compensation or credit.
• Promotions: Contests, sweepstakes, or other activities (“Promotions”) may be governed by separate rules regarding eligibility requirements such as age or location restrictions. You are responsible for reviewing all Promotion rules prior to participation.`
  },
  {
    id: "disclaimer",
    title: "22. Disclaimer",
    content: `We are not responsible for any content, code or any other imprecision. We do not provide warranties or guarantees. In no event shall we be liable for any special, direct, indirect, consequential, or incidental damages. We reserve the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.

Our Service and its contents are provided “as is” and “as available” without any warranty or representations of any kind, whether express or implied.`
  },
  {
    id: "contact-us",
    title: "23. Contact Us",
    content: `Don’t hesitate to contact us if you have any questions regarding these Terms & Conditions.

• Via Email: [sales@analyticsclouds.com](mailto:sales@analyticsclouds.com)`
  }
];

  const toggleSection = (id: string) => {
    setOpenSection(openSection === id ? null : id);
  };

  return (
    <div id="terms-of-service-page-container" className="bg-white text-[#333333] selection:bg-[#FE7146] selection:text-white">

      {/* 1. Hero Section (dark navy band, extends behind the fixed navbar — no white gap) */}
      <section id="terms-hero-section" className="bg-[#303360] text-white pt-28 pb-16 sm:pt-32 sm:pb-20 relative overflow-hidden">
        
        {/* Subtle background decoration (low opacity orange gradient and dots) */}
        <div className="absolute inset-0 z-0 opacity-15 pointer-events-none">
          <div className="absolute top-1/2 right-10 -translate-y-1/2 w-96 h-96 bg-[#FE7146] rounded-full filter blur-3xl" />
          <div className="absolute inset-0 bg-[radial-gradient(#ffffff_1px,transparent_1px)] [background-size:24px_24px] opacity-10" />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center space-y-6">
          
          {/* Small pill badge */}
          <div className="inline-block bg-white text-[#303360] text-[10px] sm:text-xs font-black tracking-widest uppercase px-4 py-1.5 rounded-full shadow-md">
            Please Read Before Using Our Platform
          </div>

          {/* Headline */}
          <h1 className="font-display font-extrabold text-4xl sm:text-5xl lg:text-6xl text-white tracking-tight leading-tight">
            Terms of Service
          </h1>

          {/* Subcopy */}
          <p className="text-gray-300 text-sm sm:text-base font-normal max-w-2xl mx-auto leading-relaxed">
            By accessing the Analytics Clouds website or using our data-driven growth solutions, you agree to comply with and be bound by the following legal guidelines.
          </p>

        </div>
      </section>

      {/* 2. Breadcrumb bar */}
      <section id="terms-breadcrumb-bar" className="bg-[#F5F5FA] border-b border-gray-100 py-3 text-left">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-xs font-semibold text-gray-500 flex items-center gap-2">
          <Link href="/" className="text-[#303360] hover:text-[#FE7146] transition-colors">
            Home
          </Link>
          <span className="text-gray-400 font-normal">&gt;</span>
          <span className="text-[#FE7146] font-bold">Terms of Service</span>
        </div>
      </section>

      {/* 3. Terms Accordion (Main Content) */}
      <section id="terms-content-section" className="py-16 sm:py-24 bg-white relative">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          
          {/* Header metadata row */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-100 pb-6 mb-10">
            <div className="flex items-center gap-2 text-slate-500 font-semibold text-xs">
              <Clock size={14} className="text-[#FE7146]" />
              <span>Last Updated: July 2026</span>
            </div>
            
          </div>

          {/* Accordion List */}
          <div className="space-y-4">
            {termsSections.map((sec) => {
              const isOpen = openSection === sec.id;
              
              return (
                <div
                  key={sec.id}
                  id={`accordion-item-${sec.id}`}
                  className={`border rounded-2xl transition-all duration-300 overflow-hidden bg-white ${
                    isOpen
                      ? "border-[#FE7146] shadow-md shadow-[#FE7146]/5"
                      : "border-gray-200 hover:border-gray-300 hover:bg-slate-50/50"
                  }`}
                >
                  
                  {/* Clickable Header Row */}
                  <button
                    onClick={() => toggleSection(sec.id)}
                    className="w-full px-6 py-4.5 sm:py-5 flex items-center justify-between gap-4 text-left cursor-pointer focus:outline-none min-h-[52px]"
                    aria-expanded={isOpen}
                  >
                    <span className={`font-display font-black text-sm sm:text-base transition-colors ${
                      isOpen ? "text-[#303360]" : "text-[#303360]/85"
                    }`}>
                      {sec.title}
                    </span>

                    {/* Rotating chevron indicator */}
                    <div className={`shrink-0 w-7 h-7 rounded-full border flex items-center justify-center transition-all duration-300 ${
                      isOpen 
                        ? "border-[#FE7146]/20 bg-[#FFF1EC] text-[#FE7146]" 
                        : "border-gray-200 bg-slate-50 text-slate-400"
                    }`}>
                      <ChevronDown
                        size={15}
                        className={`transition-transform duration-300 ${isOpen ? "rotate-180" : ""}`}
                      />
                    </div>
                  </button>

                  {/* Expandable Body Panel with height-animation */}
                  <AnimatePresence initial={false}>
                    {isOpen && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden border-t border-gray-100 bg-slate-50/20"
                      >
                        <div className="px-6 py-5 sm:py-6 text-gray-600 text-xs sm:text-sm font-normal leading-relaxed text-left whitespace-pre-wrap">
                          {sec.content}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>

                </div>
              );
            })}
          </div>

        </div>
      </section>

      {/* 4. "Still Have Questions?" Closing Strip */}
      <section id="terms-questions-strip" className="py-12 bg-[#F5F5FA] border-t border-b border-gray-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-6">
          
          <div className="flex items-center gap-4 text-left">
            <div className="w-10 h-10 rounded-full bg-[#FFF1EC] text-[#FE7146] flex items-center justify-center shrink-0 shadow-sm">
              <HelpCircle size={20} />
            </div>
            <div>
              <h3 className="font-display font-black text-sm sm:text-base text-[#303360] leading-snug">
                Have questions about these terms?
              </h3>
              <p className="text-gray-500 text-xs mt-0.5 font-medium">
                Our administrative squad is ready to assist with any legal or SLA clarifications.
              </p>
            </div>
          </div>

          <Link href="/contact"
            className="w-full sm:w-auto bg-[#FE7146] hover:bg-[#e0562b] text-white font-extrabold text-xs px-6 py-3.5 rounded-xl shadow-md hover:shadow-lg hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center justify-center gap-1.5"
          >
            <span>Contact Our Team</span>
            <ArrowRight size={14} />
          </Link>

        </div>
      </section>

    </div>
  );
}
